---
- name: nginx-exp group
  become: true
  group:
    name: nginx-exp
    state: present
    system: yes

- name: Add the user 'nginx-exp'
  become: true
  user:
    name: nginx-exp
    comment: Nginx Prometheus Exporter
    group: nginx-exp

- name: Download nginx-exporter
  become: true
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: ~/Downloads/
    force_basic_auth: yes

- name: Extract nginx-exporter
  become: true
  unarchive:
    src: ~/Downloads/nginx-prometheus-exporter-0.3.0-linux-i386.tar.gz
    dest: ~/Downloads/

- name: Template a file to /etc/files.conf
  template:
    src: /template/prom-exporter.j2
    dest: /etc/systemd/system/nginx_exporter.service
    owner: bin
    group: wheel
    mode: '0644'

- name: start nginx_exporter
  become: true
  package:
    name: nginx_exporter
    state: present
  notify: start nginx-exporter
