---
- name: nginx-exp group
  become: true
  group:
    name: "{{ nginx_group }}"
    state: present
    system: yes

- name: Add the user 'nginx-exp'
  become: true
  user:
    name: "{{ nginx_user }}"
    comment: Nginx Prometheus Exporter
    groups: {{ nginx_group }}

#download only

#- name: Download nginx-exporter
#  become: true
#  get_url:
#    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
#    dest: /tmp/
#    force_basic_auth: yes

#download from remote & unarchive

- name: Extract nginx-exporter
  become: true
  unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Template a file over
  template:
    src: ./template/prom-exporter.j2
    dest: /etc/systemd/system/nginx_exporter.service
    mode: '0644'

- name: enable nginx_exporter
  become: true
  systemd:
    name: nginx_exporter
    enabled: yes
    state: started
